INSERT INTO persons (person_id, name) VALUES (default, '홍길동');
INSERT INTO persons (person_id, name) VALUES (default, '임꺽정');
INSERT INTO persons (person_id, name) VALUES (default, '심봉사');
INSERT INTO persons (person_id, name) VALUES (default, '김영희');
INSERT INTO persons (person_id, name) VALUES (default, '5번');
INSERT INTO persons (person_id, name) VALUES (default, '김팀장');
INSERT INTO persons (person_id, name) VALUES (default, '이팀장');
INSERT INTO persons (person_id, name) VALUES (default, '박팀장');
INSERT INTO persons (person_id, name) VALUES (default, '최팀장');
INSERT INTO persons (person_id, name) VALUES (default, '10번');

INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'pytho 튜플 스터디 - 1/5', 4, 1);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'pyqt5 화면 만들기 - 2/4', 4, 1);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'mysql 테이블 생성 (18시까지)', 3, 1);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'mysql 권한 수정 (오늘까지)', 3, 1);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'vue.js 수정화면 리뷰', 2, 1);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'pytho 튜플 스터디', 4, 2);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'pyqt5 화면 만들기', 4, 2);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'mysql 테이블 생성', 4, 2);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'mysql 권한 수정', 4, 2);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'vue.js 수정화면 리뷰', 4, 2);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, '경영지원팀에 문서1 전달 (18시까지)', 3, 3);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, '심봉사님께 문서1 요청 (15시까지)', 4, 4);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'typescript 에러 리뷰', 2, 6);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'pytho 튜플 스터디 리뷰', 4, 7);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'pyqt5 화면 만들기 리뷰', 4, 7);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'mysql 테이블 생성 리뷰', 4, 7);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'mysql 권한 수정 리뷰', 3, 7);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'vue.js 수정화면 실행 & 리뷰', 3, 7);
INSERT INTO todolists (id, content, state, person_id) VALUES (default, 'SQL 구문 생성', 2, 8);